server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#token:
#  expiration_time: 864000000 #10 days
#  secret: userTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserTokenuserToken

logging:
  level:
    org:
      hibernate:
        SQL: debug
    com.example.userservice: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.applilcation.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce.

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,beans # 제공되는.. 사용할 end point
        # refresh : config 정보 알아서 refresh 하겠다 (post요청해야함)