server:
  port: 8888
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/imnooy/spring-clound-config.git
#          username: username입력
#          password: password입력
